server:
  port: 8081

spring:
  application:
    name: bruce-zhu
  datasource:
    url: jdbc:mysql://117.78.44.77:3306/geebox_2_0?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: SaRFq2Nm%Wd2*tM4
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 20
      initialSize: 5
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      removeAbandoned: true
      removeAbandonedTimeout: 300000

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #??sql??
    map-underscore-to-camel-case: true
    cache-enabled: false
    global-config:
      db-config:
        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
        id-type: 0
        #驼峰下划线转换
        table-underline: true
        update-strategy: ignored

config:
  es:
    addr: 192.168.140.215
    port: 9200
  redis:
    host: 114.116.52.156
    port: 65057
    password: QeXPfCe3ht@wvFvC
    index: 0
    timeout: 10000
    maxWait: -1
    maxIdle: 5
    minIdle: 1
    MaxWaitMillis: 10000
    MaxTotal: 5
    TestOnBorrow: true
    UsePool: true

sms:
  enabled: false